[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["development-tools::testing", "gui"]
description = "Testing library for relm"
documentation = "https://docs.rs/relm-test/"
license = "MIT"
name = "relm-test"
repository = "https://github.com/antoyo/relm"
version = "0.14.4"

[dependencies]
enigo = "^0.0.11"
gdk = "^0.8.0"
gtk = "^0.4.0"

[dependencies.relm-core]
path = "../relm-core"
version = "^0.14.0"

[features]
default = ["gtk/v3_10"]
